import type { Mission } from "@/lib/missions";

export const initialMissions: Mission[] = [
  {
    id: "mission-01",
    title: "Mappare il settore Eissentam",
    description: "Rilevare tre pianeti e condividere i dati cartografici.",
    system: "Eissentam · K-14",
    systemAddress: "0807F07FFFFF",
    galaxy: 10,
    assignedTo: "NovaRider",
      targetSpecialty: "all",
    dueDate: "2026-10-08",
    status: "In corso",
    priority: "Alta",
    progress: 68,
  },
  {
    id: "mission-02",
    title: "Rifornimento naniti",
    description: "Consegnare naniti alla base logistica dell'alleanza.",
    system: "Euclide · V-02",
    systemAddress: "00087F001001",
    galaxy: 0,
    assignedTo: "Orion_7",
      targetSpecialty: "all",
    dueDate: "2026-10-06",
    status: "In corso",
    priority: "Urgente",
    progress: 35,
  },
  {
    id: "mission-03",
    title: "Avamposto su pianeta tossico",
    description: "Posizionare il beacon e verificare le coordinate sicure.",
    system: "Hilbert · R-88",
    systemAddress: "00097F002002",
    galaxy: 1,
    assignedTo: "LyraV",
      targetSpecialty: "all",
    dueDate: "2026-10-11",
    status: "In attesa",
    priority: "Normale",
    progress: 0,
  },
  {
    id: "mission-04",
    title: "Recupero tecnologia antica",
    description: "Esplorazione completata, reperto archiviato nella base.",
    system: "Euclide · A-31",
    systemAddress: "000A7F003003",
    galaxy: 0,
    assignedTo: "AtlasPrime",
      targetSpecialty: "all",
    dueDate: "2026-10-03",
    status: "Completata",
    priority: "Alta",
    progress: 100,
  },
];